//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDevOps.APISQL.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLPDUMPEntities : DbContext
    {
        public CLPDUMPEntities()
            : base("name=CLPDUMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountSiteMaster> AccountSiteMaster { get; set; }
        public virtual DbSet<AccountSiteTempMaster> AccountSiteTempMaster { get; set; }
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<FirePrevention> FirePrevention { get; set; }
        public virtual DbSet<FireWatchPrevention> FireWatchPrevention { get; set; }
        public virtual DbSet<HandHeldMaster> HandHeldMaster { get; set; }
        public virtual DbSet<HotWork> HotWork { get; set; }
        public virtual DbSet<HotWorkMeasure> HotWorkMeasure { get; set; }
        public virtual DbSet<Impairment> Impairment { get; set; }
        public virtual DbSet<ImpairmentClassMaster> ImpairmentClassMaster { get; set; }
        public virtual DbSet<ImpairmentMeasureMaster> ImpairmentMeasureMaster { get; set; }
        public virtual DbSet<ImpairmentPrecaution> ImpairmentPrecaution { get; set; }
        public virtual DbSet<ImpairmentPrecautionMaster> ImpairmentPrecautionMaster { get; set; }
        public virtual DbSet<ImpairmentTypeMaster> ImpairmentTypeMaster { get; set; }
        public virtual DbSet<MeasureMaster> MeasureMaster { get; set; }
        public virtual DbSet<ReporterDetail> ReporterDetail { get; set; }
        public virtual DbSet<Scope> Scope { get; set; }
        public virtual DbSet<ScopePerson> ScopePerson { get; set; }
        public virtual DbSet<ScopeWorkOrder> ScopeWorkOrder { get; set; }
        public virtual DbSet<ShutDownReasonMaster> ShutDownReasonMaster { get; set; }
        public virtual DbSet<WorkOrderMaster> WorkOrderMaster { get; set; }
    }
}
