//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDevOps.APISQL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public int Id { get; set; }
        public Nullable<int> HotWorkId { get; set; }
        public string AuthorizerName { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> AuthorizationDateTime { get; set; }
        public string IsHighHazardArea { get; set; }
        public string AreaSupervisorName { get; set; }
        public string AreaSupervisorDepartment { get; set; }
    
        public virtual HotWork HotWork { get; set; }
    }
}
