//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDevOps.APISQL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FireWatchPrevention
    {
        public int Id { get; set; }
        public Nullable<int> FirePreventionId { get; set; }
        public string PersonName { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string FireWatchType { get; set; }
    
        public virtual FirePrevention FirePrevention { get; set; }
    }
}
