//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDevOps.APISQL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirePrevention
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirePrevention()
        {
            this.FireWatchPrevention = new HashSet<FireWatchPrevention>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HotWorkId { get; set; }
        public string NearestFireAlarmLocation { get; set; }
        public string NearestPhone { get; set; }
    
        public virtual HotWork HotWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FireWatchPrevention> FireWatchPrevention { get; set; }
    }
}
