//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDevOps.APISQL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotWork()
        {
            this.Authorization = new HashSet<Authorization>();
            this.FirePrevention = new HashSet<FirePrevention>();
            this.HotWorkMeasure = new HashSet<HotWorkMeasure>();
            this.Scope = new HashSet<Scope>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HotWorkMobileId { get; set; }
        public string AccountId { get; set; }
        public string SiteId { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<int> ParentHotWorkId { get; set; }
        public string WorkFlowStatus { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authorization> Authorization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirePrevention> FirePrevention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotWorkMeasure> HotWorkMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scope> Scope { get; set; }
    }
}
