//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDevOps.APISQL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotWorkMeasure
    {
        public int Id { get; set; }
        public Nullable<int> HotWorkId { get; set; }
        public Nullable<int> MeasureId { get; set; }
        public string MeasureStatus { get; set; }
        public Nullable<int> FireHoseCount { get; set; }
        public Nullable<int> FireExtinguisherCount { get; set; }
    
        public virtual HotWork HotWork { get; set; }
        public virtual MeasureMaster MeasureMaster { get; set; }
    }
}
