//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDevOps.APISQL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpairmentPrecaution
    {
        public int ImpairmentId { get; set; }
        public int ImpairmentPrecautionMasterId { get; set; }
        public string OtherDescription { get; set; }
    
        public virtual Impairment Impairment { get; set; }
        public virtual ImpairmentPrecautionMaster ImpairmentPrecautionMaster { get; set; }
    }
}
