//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDevOps.APISQL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeWorkOrder
    {
        public int Id { get; set; }
        public Nullable<int> ScopeId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
    
        public virtual Scope Scope { get; set; }
        public virtual WorkOrderMaster WorkOrderMaster { get; set; }
    }
}
